### ISSUE TITLE
What's platform running this webcam?

### ISSUE THREAD

**Issue by Hoverhuang-er** [goh-chunlin/WebcamWinForm#1]
Which hardware hardware architecture used？ Raspberry Pi or PC??

**Comment by goh-chunlin** [comment]
PC. The program itself is written with .NET Framework 4.5.2. So yup, as long as you can get this on the platform, no problem. I doubt RasPi can support .NET Framework.

**Comment by Hoverhuang-er** [comment]
Ehmm. I search for dotnet core in IoT. And find this url: https://github.com/dotnet/core-setup and url: https://github.com/dotnet/core/issues/232. Hmm. I will try after reply this issuse. Thanks for your reply
